### pvc definition
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pvc
spec:
  accessModes:
    - ReadWriteMany  # RWX for many nodes
  resources:
    requests:
      storage: 5Gi  # size (EFS is elastic thus adjust automatically)
  storageClassName: efs-sc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: efs-app
spec:
  replicas: 3  # 3 Pods that can read and write in the same volume
  selector:
    matchLabels:
      app: efs-app
  template:
    metadata:
      labels:
        app: efs-app
    spec:
      containers:
      - name: app
        image: busybox
        command: [ "sh", "-c", "echo 'Hello from EFS!' > /data/test.txt && sleep 3600" ]
        volumeMounts:
        - mountPath: "/data"
          name: efs-storage
      volumes:
      - name: efs-storage
        persistentVolumeClaim:
          claimName: efs-pvc
#
#
# Apply the yaml file
# kubectl apply -f efs-pvc-deployment.yaml
#
# verify
# kubectl get pvc
# kubectl get pods -o wide
# kubectl exec -it <pod-name> -- cat /data/test.txt
#
# All the pods must have the same file test.txt 