
apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    kubernetes.io/metadata.name: dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: adam
  namespace: "dev" 
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "namespaces", "nodes"]
    verbs: ["create", "get", "update", "list", "watch", "patch"]
    #  - apiGroups: ["apps"]
    #    resources: ["deployment"]
    #    verbs: ["create", "get", "update", "list", "delete", "watch", "patch"]
    #  - apiGroups: ["rbac.authorization.k8s.io"]
    #    resources: ["clusterroles", "clusterrolebindings"]
    #    verbs: ["create", "get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: serge-rb
  namespace: "dev"
subjects:
  - kind: ServiceAccount
    name: adam-sa
    namespace: dev
roleRef:
  kind: Role
  name: adam
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: adam-sa
  namespace: "dev"
secrets:
  - name: adam-secret

---
apiVersion: v1
kind: Secret
metadata:
  name: adam-secret
  namespace: "dev"
  annotations:
    kubernetes.io/service-account.name: adam-sa
type: kubernetes.io/service-account-token

