apiVersion: v1
kind: Pod
metadata:
  name: pod-quota1-test
  namespace: test
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "800Mi"
        cpu: "1000m"
      requests:
        memory: "600Mi"
        cpu: "350m"